config/routes.rb
SweetArticlesRails::Application.routes.draw do
  root to: 'categories#index'

  resources :categories do
    resources :articles
  end

  resources :tags do 
    resources :articles
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_and_belongs_to_many :tags
  belongs_to :category

  def to_param
    "#{title.parameterize}"
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates_uniqueness_of :name

  def to_param
    "#{name.parameterize}"
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :articles
  validates_uniqueness_of :name

  def to_param
    "#{name.parameterize}"
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    unless (params[:category_id].nil?)
      @category = Category.find_by_name(params[:category_id])
    else
      @tag = Tag.find_by_name(params[:tag_id])
    end
  end

  def show
    @article = Article.find_by_title(params[:id].gsub('-',' '))
  end

  def new
    @article = Article.new
    @article.category = Category.find(params[:category_id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @articles = Category.all
  end

  def show
    redirect_to category_articles_path(params[:id])
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    redirect_to tag_articles_path(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<% unless @category.nil? %>
  <h3><%= @category.name %></h3>
  <ul>
    <% @category.articles.each do |article| %>
      <li><%= link_to article.title, category_article_path(@category, article) %></li>
    <% end %>
  </ul>

<% else %>
  <h3><%= @tag.name %></h3>
  <ul>
    <% @tag.articles.each do |article| %>
      <li><%= link_to article.title, tag_article_path(@tag, article) %></li>
    <% end %>
  </ul>
<% end %>

app/views/articles/new.html.erb
<h1>New Article for <%= @article.category.name %></h1>
<%= form_for [@article.category, @article] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :description %>
  <%= f.text_area :description %><br>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<article>
  <h1><%= @article.category.name %></h1>
  <h3><%= @article.title %></h3>
  <ul style="padding: 0">
    <li style="display:inline">Tags:</li>
  <% @article.tags.each do |tag|  %>
    <li style="display:inline"> <%= link_to tag.name.capitalize, tag_articles_path(tag) %> </li>
  <% end %>
  </ul>
  <hr/>
  <p><%= @article.description %></p>
</article>

app/views/categories/index.html.erb
<% @categories.each do | category| %>
  <h3><%= link_to category.name, category_path(category) %></h3>
  <ul>
    <% category.articles.each do |article| %>
      <li><%= link_to article.title, category_article_path(category, article) %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SweetArticlesRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<% @tags.each do |tag| %>
  <h3><%= link_to tag.name, tag_path(tag) %></h3>
  <ul>
    <% tag.articles.each do |article| %>
      <li><%= link_to article.title, tag_article_path(tag, article) %></li>
    <% end %>
  </ul>
<% end %>

app/views/tags/show.html.erb
<h3><%= @tag.name %></h3>
<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, tag_article_path(@tag, article) %></li>
  <% end %>
</ul>